services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=picsy_pf
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports: ["5432:5432"]
    volumes: [postgres-data:/var/lib/postgresql/data]
    networks: [picsy-net]

  backend:
    build:
      context: ./backend-java          # ★ ここに上の Dockerfile がある
      dockerfile: Dockerfile           # ★ 明示して参照ズレを撲滅
    depends_on: [db]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/picsy_pf
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_FLYWAY_ENABLED=true
    ports: ["8081:8080"]
    networks: [picsy-net]

  web:
    build:
      context: ./server-node
      dockerfile: Dockerfile
    environment:
      - BACKEND_API_URL=http://backend:8080
    ports: ["8080:3000"]
    depends_on: [backend]
    networks: [picsy-net]

volumes:
  postgres-data:

networks:
  picsy-net:
