# application-prod.properties
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.type.preferred_json_sql_type=JSONB
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none   # Flyway主導
